### PR TITLE
add w-auto and h-auto

### PR DESCRIPTION
**Pull request by jeffreyyoung**

### CODE REVIEW

**Comment by z0al** [comment]
Thanks for opening this @jeffreyyoung :clap:  

Tip: To fix linting simply update your branch with the master and run

```
yarn format
```

It looks good to me but I'm still not sure if `auto` actually works as expected. On [React Native Styling Cheat Sheet](https://github.com/vhpoet/react-native-styling-cheat-sheet#flexbox) it's written that:

> properties with default value auto marked with asterisk are do not actually have auto as their default value, they just behave like if they would in css if they had auto as their value. auto is not valid value for those properties in react-native

And both `width` and `height` are marked with `*`.

I couldn't find something in the official docs. Do you have a link for that?

**Comment by jeffreyyoung** [comment]
ooo good catch!  I saw that cheat sheet, and assumed "auto" was a valid value 🤦‍♂️. I'm struggling to find documentation on using "auto" for height and width. These are a few random things I found:

* according to the StyleSheet flow types the valid width/height values are `null | number | string` (not exactly helpful to us 😅) https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheetTypes.js#L30 

* I found one usage of height: "auto" in this test in the react-native repo https://github.com/facebook/react-native/blob/6e6443afd04a847ef23fb6254a84e48c70b45896/packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js#L222

* I see some native code about [parsing "auto" to a "yoga value"](https://github.com/facebook/react-native/blob/6e6443afd04a847ef23fb6254a84e48c70b45896/ReactAndroid/src/main/java/com/facebook/yoga/YogaValue.java#L70), and then [using auto in the context of setting width](https://github.com/facebook/react-native/blob/6e6443afd04a847ef23fb6254a84e48c70b45896/ReactAndroid/src/main/java/com/facebook/react/uimanager/LayoutShadowNode.java#L90)

From trying the following code samples I see that
* ```<View style={[{"width": 25, "height": 25, backgroundColor: "purple"}, {"width": "yay"}]}/>``` <-- this throws an error
* ```<View style={[{"width": 25, "height": 25, backgroundColor: "purple"}, {"width": "auto"}]}/>``` <-- this sets the width to behave like css auto
* ```<View style={[{"width": 25, "height": 25, backgroundColor: "purple"}, {"width": null}]}/>``` <-- this also sets the width to behave like css auto

Honestly not 100% sure if "auto" is actually a supported value since it isn't well documented, however since I notice it's handled in the code I think it miiiight be. 🤷‍♂️

anyways I've been using this library in a side project and am really enjoying it and appreciate your work!

**Comment by z0al** [comment]
Wow, great research, Thanks :)

The React Native example & Yoga code are enough for me to continue with this PR. We can always investigate this again if someone reports otherwise.

**Review by z0al — APPROVED** [review]
LGTM. Thank you :bow: 

A `git rebase` & `yarn format` should fix the conflicts & lining issues.

**Comment by jeffreyyoung** [comment]
sounds good!  Just updated the pr

**Pull request merged**
